const MDP_BASE="/mydealsportal-preview/";
const seedDeals=[
{id:"sample-1",title:"20% Off Dinner for Two",business:"Harbor Table Kitchen",zip:"04101",city:"Portland, Maine",category:"Food & Drink",price:"Save 20%",description:"Enjoy 20% off two dinner entrées during select evening hours.",terms:"Dine-in only. Sample ad for preview purposes.",created:8,active:true,sample:true},
{id:"sample-2",title:"$30 Off Full Interior Detail",business:"Pine State Auto Detail",zip:"04005",city:"Biddeford, Maine",category:"Automotive",price:"Save $30",description:"Save on a complete interior detail for cars, trucks, and SUVs.",terms:"Appointment required. Sample ad for preview purposes.",created:7,active:true,sample:true},
{id:"sample-3",title:"Free Trim With Color Service",business:"Coastal Glow Salon",zip:"04074",city:"Scarborough, Maine",category:"Beauty & Personal Care",price:"Free add-on",description:"Book a qualifying color service and receive a complimentary trim.",terms:"New clients only. Sample ad for preview purposes.",created:6,active:true,sample:true},
{id:"sample-4",title:"First Class Free",business:"Southern Maine Strength Co.",zip:"04072",city:"Saco, Maine",category:"Health & Fitness",price:"Free",description:"Try your first group fitness class free before choosing a membership.",terms:"First-time visitors only. Sample ad for preview purposes.",created:5,active:true,sample:true},
{id:"sample-5",title:"15% Off Local Gifts",business:"Main Street Mercantile",zip:"04043",city:"Kennebunk, Maine",category:"Gifts & Specialty",price:"Save 15%",description:"Save on a qualifying purchase of locally made gifts and specialty goods.",terms:"Some exclusions apply. Sample ad for preview purposes.",created:4,active:true,sample:true},
{id:"sample-6",title:"Free Home Value Consultation",business:"Coastal Maine Realty Group",zip:"04072",city:"Saco, Maine",category:"Real Estate & Property",price:"Free",description:"Get a no-obligation local market review and estimated home value consultation.",terms:"By appointment. Sample ad for preview purposes.",created:3,active:true,sample:true},
{id:"sample-7",title:"$25 Off First Grooming Visit",business:"Happy Tails Pet Care",zip:"04011",city:"Brunswick, Maine",category:"Pet Services",price:"Save $25",description:"New customers save on their pet’s first full grooming appointment.",terms:"New clients only. Sample ad for preview purposes.",created:2,active:true,sample:true},
{id:"sample-8",title:"Buy One Admission, Get One 50% Off",business:"Maine Family Fun Center",zip:"04092",city:"Westbrook, Maine",category:"Things To Do",price:"50% off second",description:"Bring a friend or family member and save on the second admission.",terms:"Same-day admission only. Sample ad for preview purposes.",created:1,active:true,sample:true}
];
function esc(s){return String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function customDeals(){return JSON.parse(localStorage.getItem("mdp_demo_deals")||"[]")}
function allDeals(includePaused=false){const all=seedDeals.concat(customDeals());return includePaused?all:all.filter(d=>d.active!==false)}
function getDeal(id){return allDeals(true).find(d=>String(d.id)===String(id))}
function businessDeals(name){return allDeals().filter(d=>d.business===name)}
function nav(){return '<header><div class="wrap nav"><a class="brand" href="'+MDP_BASE+'">My<span>Deals</span>Portal</a><nav class="navlinks"><a href="'+MDP_BASE+'#deals">Find Deals</a><a href="'+MDP_BASE+'advertise.html">For Businesses</a><a href="'+MDP_BASE+'faq.html">FAQ</a><a href="'+MDP_BASE+'login.html">Business Login</a><a class="btn btn-primary" href="'+MDP_BASE+'advertise.html">Advertise</a></nav></div></header>'}
function footer(){return '<footer class="footer"><div class="wrap">© 2026 MyDealsPortal · <a href="'+MDP_BASE+'privacy.html">Privacy</a> · <a href="'+MDP_BASE+'terms.html">Terms</a> · <a href="'+MDP_BASE+'advertiser-terms.html">Advertiser Terms</a> · <a href="'+MDP_BASE+'faq.html">FAQ</a> · <a href="'+MDP_BASE+'contact.html">Contact</a></div></footer>'}
function businessInfo(name){const b=JSON.parse(localStorage.getItem("mdp_demo_business")||"null");return b&&b.name===name?b:null}
function businessHref(d){return d.businessId?MDP_BASE+'business.html?id='+encodeURIComponent(d.businessId):MDP_BASE+'business.html?name='+encodeURIComponent(d.business)}
function dealCard(d){return '<article class="card"><div class="card-badges"><span class="pill">'+esc(d.category)+'</span>'+(d.sample?'<span class="sample-badge">SAMPLE AD</span>':'')+'</div><div class="deal-title">'+esc(d.title)+'</div><div class="business">'+esc(d.business)+'</div><div class="meta">'+esc(d.city)+' · '+esc(d.zip)+'</div><div class="price">'+esc(d.price)+'</div><p>'+esc(d.description)+'</p><div class="tiny">'+esc(d.terms)+'</div><div class="actions"><a class="btn btn-soft" href="'+MDP_BASE+'deal.html?id='+encodeURIComponent(d.id)+'">View Deal</a><a class="btn btn-ghost" href="'+businessHref(d)+'">More from this business</a></div></article>'}