const MDP_BASE="/mydealsportal-preview/";
const seedDeals=[
{id:"1",title:"Save 15% on Interior Painting",business:"New Leaf Painting Company",zip:"04072",city:"Saco, Maine",category:"Home Services",price:"Save 15%",description:"Limited-time savings on qualifying interior painting projects.",terms:"Limited availability this month.",created:6,active:true},
{id:"2",title:"Family Pizza Night Special",business:"Example Pizza Co.",zip:"04101",city:"Portland, Maine",category:"Restaurants",price:"$29.99",description:"Family-size pizza bundle with sides for one simple price.",terms:"Tuesday through Thursday.",created:5,active:true},
{id:"3",title:"$25 Off Full Auto Detail",business:"Example Auto Detail",zip:"04005",city:"Biddeford, Maine",category:"Automotive",price:"Save $25",description:"Seasonal cleanup special for cars, trucks and SUVs.",terms:"Appointment required.",created:4,active:true},
{id:"4",title:"Free Brow Wax With Color Service",business:"Example Salon",zip:"04074",city:"Scarborough, Maine",category:"Health & Beauty",price:"Free add-on",description:"Book a qualifying color service and receive a brow wax.",terms:"One per customer.",created:3,active:true},
{id:"5",title:"10% Off Any Purchase Over $50",business:"Example Local Shop",zip:"04043",city:"Kennebunk, Maine",category:"Retail",price:"Save 10%",description:"Shop local and save on purchases over $50.",terms:"Some exclusions apply.",created:2,active:true},
{id:"6",title:"$100 Off Kitchen Cabinet Painting",business:"New Leaf Painting Company",zip:"04072",city:"Saco, Maine",category:"Home Services",price:"Save $100",description:"Save on a qualifying cabinet refinishing project.",terms:"New bookings only.",created:1,active:true}
];
function esc(s){return String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function customDeals(){return JSON.parse(localStorage.getItem("mdp_demo_deals")||"[]")}
function allDeals(includePaused=false){const all=seedDeals.concat(customDeals());return includePaused?all:all.filter(d=>d.active!==false)}
function getDeal(id){return allDeals(true).find(d=>String(d.id)===String(id))}
function businessDeals(name){return allDeals().filter(d=>d.business===name)}
function nav(){return '<header><div class="wrap nav"><a class="brand" href="'+MDP_BASE+'">My<span>Deals</span>Portal</a><nav class="navlinks"><a href="'+MDP_BASE+'#deals">Find Deals</a><a href="'+MDP_BASE+'advertise.html">For Businesses</a><a href="'+MDP_BASE+'faq.html">FAQ</a><a href="'+MDP_BASE+'login.html">Business Login</a><a class="btn btn-primary" href="'+MDP_BASE+'advertise.html">Advertise</a></nav></div></header>'}
function footer(){return '<footer class="footer"><div class="wrap">© 2026 MyDealsPortal · <a href="'+MDP_BASE+'privacy.html">Privacy</a> · <a href="'+MDP_BASE+'terms.html">Terms</a> · <a href="'+MDP_BASE+'advertiser-terms.html">Advertiser Terms</a> · <a href="'+MDP_BASE+'faq.html">FAQ</a> · <a href="'+MDP_BASE+'contact.html">Contact</a></div></footer>'}
function businessInfo(name){const b=JSON.parse(localStorage.getItem("mdp_demo_business")||"null");return b&&b.name===name?b:null}
function businessHref(d){return d.businessId?MDP_BASE+'business.html?id='+encodeURIComponent(d.businessId):MDP_BASE+'business.html?name='+encodeURIComponent(d.business)}
function dealCard(d){return '<article class="card"><span class="pill">'+esc(d.category)+'</span><div class="deal-title">'+esc(d.title)+'</div><div class="business">'+esc(d.business)+'</div><div class="meta">'+esc(d.city)+' · '+esc(d.zip)+'</div><div class="price">'+esc(d.price)+'</div><p>'+esc(d.description)+'</p><div class="tiny">'+esc(d.terms)+'</div><div class="actions"><a class="btn btn-soft" href="'+MDP_BASE+'deal.html?id='+encodeURIComponent(d.id)+'">View Deal</a><a class="btn btn-ghost" href="'+businessHref(d)+'">More from this business</a></div></article>'}