import { auth, db } from './firebase-dev.js';
import { onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js';
import { addDoc, collection, deleteDoc, doc, getDoc, getDocs, onSnapshot, query, serverTimestamp, setDoc, where } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';

let currentUser=null,posts=[],initialized=false;
let initialPostIds=new Set();
const followId=(followerId,targetId)=>`${followerId}_${targetId}`;
const style=document.createElement('style');
style.textContent=`.post-follow-button{margin-left:auto;border:1px solid #0ccfbd;border-radius:999px;padding:6px 10px;background:#0d0d0d;color:#0ccfbd;font:inherit;font-size:.75rem;font-weight:900;cursor:pointer}.post-follow-button.is-active{background:#0ccfbd;color:#06110f}`;
document.head.appendChild(style);

function findPost(article){const link=article.querySelector('.community-author');const authorId=link?new URL(link.href,location.href).searchParams.get('id'):'';const bodyEl=article.querySelector('.community-post-body');const body=bodyEl?.dataset.fullContent||bodyEl?.textContent||'';return posts.find(post=>post.authorId===authorId&&(post.content||'')===body)}

async function installButtons(){if(!currentUser)return;for(const article of document.querySelectorAll('.community-post')){if(article.dataset.followReady==='true')continue;const post=findPost(article);if(!post||!post.authorId||post.authorId===currentUser.uid)continue;article.dataset.followReady='true';const header=article.querySelector('.community-post-header');if(!header)continue;const button=document.createElement('button');button.type='button';button.className='post-follow-button';button.textContent='Follow';header.appendChild(button);const ref=doc(db,'follows',followId(currentUser.uid,post.authorId));const refresh=async()=>{const snap=await getDoc(ref);button.classList.toggle('is-active',snap.exists());button.textContent=snap.exists()?'Following':'Follow'};button.addEventListener('click',async()=>{button.disabled=true;try{const snap=await getDoc(ref);if(snap.exists())await deleteDoc(ref);else await setDoc(ref,{followerId:currentUser.uid,targetId:post.authorId,targetName:post.authorName||'Profile',targetType:post.accountType||'member',createdAt:serverTimestamp()});await refresh()}catch(error){console.error(error);alert(error?.code==='permission-denied'?'Follow permissions are not enabled yet.':'Follow could not be updated.')}finally{button.disabled=false}});refresh().catch(console.error)}}

async function notifyFollowers(post){if(!currentUser||post.authorId!==currentUser.uid)return;try{const snap=await getDocs(query(collection(db,'follows'),where('targetId','==',currentUser.uid)));for(const followerDoc of snap.docs){const follower=followerDoc.data();if(!follower.followerId||follower.followerId===currentUser.uid)continue;const marker=doc(db,'postFollowerNotifications',`${post.id}_${follower.followerId}`);if((await getDoc(marker)).exists())continue;await addDoc(collection(db,'notifications'),{recipientId:follower.followerId,actorId:currentUser.uid,actorName:post.authorName||'BANDtroductions Member',type:'new-post',message:'published a new community post.',linkUrl:`profile.html?id=${encodeURIComponent(currentUser.uid)}`,read:false,createdAt:serverTimestamp()});await setDoc(marker,{postId:post.id,recipientId:follower.followerId,createdAt:serverTimestamp()})}}catch(error){console.warn('Follower notifications unavailable',error)}}

const feed=document.getElementById('feed');if(feed)new MutationObserver(installButtons).observe(feed,{childList:true,subtree:true});
onAuthStateChanged(auth,user=>{currentUser=user;installButtons()});
onSnapshot(collection(db,'posts'),snapshot=>{posts=snapshot.docs.map(d=>({id:d.id,...d.data()}));if(!initialized){initialPostIds=new Set(posts.map(p=>p.id));initialized=true;installButtons();return}snapshot.docChanges().filter(change=>change.type==='added'&&!initialPostIds.has(change.doc.id)).forEach(change=>notifyFollowers({id:change.doc.id,...change.doc.data()}));posts.forEach(p=>initialPostIds.add(p.id));document.querySelectorAll('.community-post').forEach(a=>delete a.dataset.followReady);installButtons()});