import './welcome-popup.js?v=1';
import { initializeApp, getApps } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js';
import { getDatabase, ref, onValue, runTransaction } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-database.js';
import { getFirestore, doc, onSnapshot, runTransaction as runFirestoreTransaction, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
import { activePlaylist, playlistPosition } from './radio-schedule-engine.js?v=2';

function setupDashboardChrome(){const header=document.querySelector('.sticky-header'),grid=document.querySelector('.grid');if(!header||!grid)return;const style=document.createElement('style');style.id='dashboard-fixed-header-style';style.textContent=`
.sticky-header{position:fixed!important;top:0!important;left:50%!important;transform:translateX(-50%)!important;width:min(calc(100% - 24px),1476px)!important;z-index:5000!important;background:#090a0a!important;box-shadow:0 8px 18px rgba(0,0,0,.72)!important}.top{position:relative!important}.brand-block{display:flex!important;align-items:center!important;justify-content:flex-start!important;gap:14px!important;min-width:0!important}.brand-copy{display:flex!important;flex-direction:column!important;justify-content:center!important;min-width:0!important}.header-logo-frame{width:112px!important;height:82px!important;display:flex!important;align-items:center!important;justify-content:center!important;overflow:visible!important;flex:0 0 112px!important;align-self:center!important}.header-logo{width:100%!important;height:100%!important;max-width:none!important;object-fit:contain!important;object-position:center!important;display:block!important;transform:scale(1.12)!important;transform-origin:center!important}.scene-view-counter{display:none!important}.news-scroller-card{height:40px!important;grid-template-columns:66px minmax(0,1fr)!important}.news-label{font-size:11px!important;line-height:.92!important}.news-group{font-size:12px!important;gap:25px!important;padding:0 12px!important}.radio-panel{position:relative!important;overflow:hidden!important;min-width:0!important}.right,.center,.left{min-width:0!important}.right{max-width:100%!important}.right .panel{max-width:100%!important}.dashboard-radio-actions{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:6px}.dashboard-radio-actions .btn{display:flex!important;align-items:center;justify-content:center;text-align:center;min-width:0;padding-left:5px!important;padding-right:5px!important}.dashboard-radio-actions .dashboard-radio-sponsor{grid-column:1/-1}.dashboard-radio-play{margin-top:10px!important}.radio-live-badge{position:absolute;z-index:20;top:11px;right:8px;width:86px;text-align:center;background:#991b1b;color:#fff;border:1px solid #ff5a5a;padding:5px 6px;font-size:9px;font-weight:950;letter-spacing:.06em;transform:rotate(9deg);box-shadow:0 3px 10px rgba(0,0,0,.65);pointer-events:none;text-transform:uppercase;white-space:nowrap}
@media(max-width:1000px){.sticky-header{width:calc(100% - 12px)!important}.brand-block{gap:10px!important}.header-logo-frame{width:94px!important;height:70px!important;flex-basis:94px!important}.news-scroller-card{height:31px!important;grid-template-columns:56px minmax(0,1fr)!important}.news-label{font-size:9px!important}.news-group{font-size:10px!important;gap:20px!important;padding:0 10px!important}.grid{grid-template-columns:minmax(0,23fr) minmax(0,50fr) minmax(0,27fr)!important;gap:6px!important;width:100%!important;max-width:100%!important;overflow:hidden!important}.right,.right .panel{width:100%!important;max-width:100%!important;overflow:hidden!important}}
@media(max-width:650px){.sticky-header{width:calc(100% - 8px)!important}.brand-block{gap:7px!important}.header-logo-frame{width:76px!important;height:60px!important;flex-basis:76px!important}.news-scroller-card{height:26px!important;grid-template-columns:48px minmax(0,1fr)!important}.news-label{font-size:7px!important}.news-group{font-size:7.5px!important;gap:15px!important;padding:0 8px!important}.grid{grid-template-columns:minmax(0,23fr) minmax(0,51fr) minmax(0,26fr)!important;gap:3px!important;width:100%!important;max-width:100%!important;overflow:hidden!important}.right{width:100%!important;max-width:100%!important;padding:0!important;margin:0!important;overflow:hidden!important}.right .panel{width:100%!important;max-width:100%!important;margin:0!important;overflow:hidden!important}.dashboard-radio-actions{gap:3px!important;margin-top:3px!important}.dashboard-radio-actions .btn{font-size:5.5px!important;padding:4px 2px!important;line-height:1.05!important;white-space:normal!important}.dashboard-radio-play{font-size:6.5px!important;padding:5px 3px!important;margin-top:5px!important}.radio-live-badge{top:5px;right:3px;width:51px;font-size:4.8px;padding:2px}}
`;document.head.appendChild(style);const nav=[...document.querySelectorAll('.nav a')];const community=nav.find(a=>a.textContent.trim().toUpperCase()==='COMMUNITY');if(community){community.textContent='GEAR EXCHANGE';community.href='gear-exchange.html';}const sync=()=>grid.style.marginTop=`${Math.ceil(header.getBoundingClientRect().height)+12}px`;sync();requestAnimationFrame(sync);window.addEventListener('resize',sync,{passive:true});if('ResizeObserver'in window)new ResizeObserver(sync).observe(header);}
setupDashboardChrome();

const cfg={apiKey:'AIzaSyApLiiJsKTw1Fp8J3aQatMqiSZoP_6EycE',authDomain:'bandfanwall.firebaseapp.com',databaseURL:'https://bandfanwall-default-rtdb.firebaseio.com',projectId:'bandfanwall',storageBucket:'bandfanwall.firebasestorage.app',messagingSenderId:'619241154826',appId:'1:619241154826:web:25ddc58eef094e3c0732f3'};
const app=getApps().find(a=>a.options?.projectId===cfg.projectId)||initializeApp(cfg,'dashboard-radio');const db=getDatabase(app),firestoreDb=getFirestore(app);const PLAYLIST_PATH='RadioTracks/__station';const panel=document.querySelector('.radio-panel'),headerPlayer=document.querySelector('.mini-player'),DEFAULT_COVER='IMG_9367.png',VIEW_COUNTER_SEED=11000;let playlists={},tracks={},audio=null,currentKey='',userWantsPlay=false,switching=false,lastCounted='';
const esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function renderSceneViewNumber(counter,value){const digits=String(Math.max(VIEW_COUNTER_SEED,Number(value)||VIEW_COUNTER_SEED)).padStart(7,'0').slice(-7);counter.querySelector('.scene-view-digits').innerHTML=[...digits].map(d=>`<span class="scene-view-digit">${d}</span>`).join('');}
function setupSceneViewCounter(){const top=document.querySelector('.top');if(!top||top.querySelector('.scene-view-counter'))return;const counter=document.createElement('div');counter.className='scene-view-counter';counter.innerHTML='<div class="scene-view-label">PAGE VIEWS</div><div class="scene-view-digits"></div>';top.appendChild(counter);renderSceneViewNumber(counter,VIEW_COUNTER_SEED);const viewsDoc=doc(firestoreDb,'siteStats','homepage');onSnapshot(viewsDoc,s=>renderSceneViewNumber(counter,s.exists()?s.data()?.views:VIEW_COUNTER_SEED),()=>renderSceneViewNumber(counter,VIEW_COUNTER_SEED));const increment=()=>runFirestoreTransaction(firestoreDb,async t=>{const s=await t.get(viewsDoc);if(!s.exists())t.set(viewsDoc,{views:VIEW_COUNTER_SEED+1,updatedAt:serverTimestamp()});else t.update(viewsDoc,{views:Math.max(VIEW_COUNTER_SEED,Number(s.data()?.views)||VIEW_COUNTER_SEED)+1,updatedAt:serverTimestamp()});});try{if(!sessionStorage.getItem('bandtroductions-home-view-counted-v2')){sessionStorage.setItem('bandtroductions-home-view-counted-v2','1');increment().catch(()=>{});}}catch{increment().catch(()=>{});}}
setupSceneViewCounter();
function approvedFallback(){return Object.entries(tracks).map(([id,t])=>({id,...t})).filter(t=>t.approved===true&&t.audioUrl&&Number(t.durationSeconds)>0).sort((a,b)=>String(a.artist||'').localeCompare(String(b.artist||'')));}
function fallbackPlaylist(){const items=approvedFallback().map(t=>({type:'track',id:t.id,title:t.title,artist:t.artist,audioUrl:t.audioUrl,coverUrl:t.coverUrl||'',profileUrl:t.profileUrl||'',durationSeconds:t.durationSeconds}));return items.length?{id:'fallback',name:'BANDtroductions Radio Rotation',days:['every'],startMinutes:0,endMinutes:1440,items,active:true}:null;}
function state(){const p=activePlaylist(playlists)||fallbackPlaylist();if(!p)return null;const pos=playlistPosition(p);return pos?{p,pos,item:p.items[pos.index]}:null;}
function actions(){return '<div class="dashboard-radio-actions"><a class="btn" href="radio.html">PLAYLIST</a><a class="btn" href="radio-submit.html">PLAY OUR SONGS</a><a class="btn dashboard-radio-sponsor" href="radio-sponsor.html">SPONSOR RADIO</a></div>';}
function countPlay(item){if(item.type!=='track'||!item.id)return;const marker=`${item.id}-${Math.floor(Date.now()/10000)}`;if(lastCounted===marker)return;lastCounted=marker;runTransaction(ref(db,`RadioTracks/${item.id}/playCount`),v=>(v||0)+1).catch(()=>{});}
function render(){if(!panel)return;const s=state(),heading=panel.querySelector('h3');panel.replaceChildren();if(heading)panel.appendChild(heading);if(!s){const d=document.createElement('div');d.className='radio';d.innerHTML=`<div class="radio-box"><small>RADIO</small><h2 style="color:var(--teal);margin:6px 0">No scheduled playlist</h2><div style="color:#999">Build a playlist in the Control Room.</div><a class="btn primary dashboard-radio-play" style="display:block;text-align:center" href="radio.html">OPEN RADIO</a>${actions()}</div>`;panel.appendChild(d);return;}const {p,item}=s;const d=document.createElement('div');d.className='radio';d.innerHTML=`<div class="radio-box"><div class="now"><img class="cover" src="${esc(item.coverUrl||DEFAULT_COVER)}" alt="artwork" style="object-fit:cover"><div><small>NOW PLAYING</small><h2 style="margin:5px 0;color:var(--teal)">${esc(item.type==='sponsor'?`Sponsor: ${item.title}`:item.title||'Untitled')}</h2><div>${esc(item.artist||'')}</div><div style="color:#888;margin-top:2px">${esc(p.name||'')}</div></div></div><div class="wave"></div><button type="button" class="btn primary dashboard-radio-play" style="display:block;width:100%;text-align:center;cursor:pointer">${audio&&!audio.paused&&userWantsPlay?'❚❚ PAUSE RADIO':'▶ PLAY RADIO'}</button>${actions()}</div>`;panel.appendChild(d);const badge=document.createElement('div');badge.className='radio-live-badge';badge.textContent='● LIVE';panel.appendChild(badge);if(headerPlayer)headerPlayer.innerHTML=`<b>● LIVE RADIO</b><div style="margin-top:8px">${esc(item.title||'BANDtroductions Radio')}</div>`;d.querySelector('.dashboard-radio-play').addEventListener('click',toggle);}
async function synchronize(playAfter=false){const s=state();if(!s)return;const {p,pos,item}=s,src=item.audioUrl||'';if(!src)return;const key=`${p.id}|${pos.index}|${item.id||item.title}`,abs=new URL(src,location.href).href;if(!audio){audio=new Audio();audio.preload='metadata';audio.addEventListener('pause',()=>{if(!switching)userWantsPlay=false;});audio.addEventListener('play',()=>{userWantsPlay=true;countPlay(state()?.item||{});});}if(audio.src!==abs||currentKey!==key){const resume=playAfter||userWantsPlay;switching=true;currentKey=key;audio.src=src;audio.load();audio.addEventListener('loadedmetadata',()=>{try{audio.currentTime=Math.min(pos.offsetSeconds,Math.max(0,(audio.duration||pos.offsetSeconds+1)-.25));}catch{}switching=false;if(resume)audio.play().catch(()=>{});render();},{once:true});return;}if(audio.readyState>0&&Math.abs((audio.currentTime||0)-pos.offsetSeconds)>3){try{audio.currentTime=pos.offsetSeconds;}catch{}}}
function toggle(){if(audio&&!audio.paused){userWantsPlay=false;audio.pause();render();return;}userWantsPlay=true;synchronize(true);render();}
onValue(ref(db,PLAYLIST_PATH),s=>{playlists=s.val()||{};render();synchronize(false);});onValue(ref(db,'RadioTracks'),s=>{tracks=s.val()||{};render();synchronize(false);});setInterval(()=>{render();if(userWantsPlay)synchronize(true);},1000);
