import { initializeApp, getApps } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js';
import { getDatabase, ref, onValue, runTransaction } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-database.js';
import { activePlaylist, playlistPosition } from './radio-schedule-engine.js?v=2';

const cfg={apiKey:'AIzaSyApLiiJsKTw1Fp8J3aQatMqiSZoP_6EycE',authDomain:'bandfanwall.firebaseapp.com',databaseURL:'https://bandfanwall-default-rtdb.firebaseio.com',projectId:'bandfanwall',storageBucket:'bandfanwall.firebasestorage.app',messagingSenderId:'619241154826',appId:'1:619241154826:web:25ddc58eef094e3c0732f3'};
const app=getApps().find(a=>a.name==='radio-public')||initializeApp(cfg,'radio-public');const db=getDatabase(app);
const PLAYLIST_PATH='RadioTracks/__station';
const audio=document.getElementById('audioPlayer'),cover=document.getElementById('trackCover'),title=document.getElementById('trackTitle'),artist=document.getElementById('trackArtist'),profile=document.getElementById('profileLink'),recent=document.getElementById('recentList');
const DEFAULT_COVER='IMG_9367.png';let playlists={},tracks={},currentKey='',userWantsPlay=false,switching=false,lastCounted='';

const esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[c]));
function approvedFallback(){return Object.entries(tracks).map(([id,t])=>({id,...t})).filter(t=>t.approved===true&&t.audioUrl&&Number(t.durationSeconds)>0).sort((a,b)=>String(a.artist||'').localeCompare(String(b.artist||'')));}
function fallbackPlaylist(){const items=approvedFallback().map(t=>({type:'track',id:t.id,title:t.title,artist:t.artist,audioUrl:t.audioUrl,coverUrl:t.coverUrl||'',profileUrl:t.profileUrl||'',durationSeconds:t.durationSeconds}));return items.length?{id:'fallback',name:'BANDtroductions Radio Rotation',days:['every'],startMinutes:0,endMinutes:1440,items,active:true}:null;}
function station(){return activePlaylist(playlists)||fallbackPlaylist();}
function currentState(){const p=station();if(!p)return null;const pos=playlistPosition(p);if(!pos)return null;return {playlist:p,pos,item:p.items[pos.index]};}
function setMetadata(item,p){cover.src=item.coverUrl||DEFAULT_COVER;title.textContent=item.type==='sponsor'?`Sponsor: ${item.title||'BANDtroductions Radio Sponsor'}`:(item.title||'Untitled Track');artist.textContent=item.type==='sponsor'?(item.artist||'Station Sponsor'):`${item.artist||'Unknown Artist'}${p?.name?` • ${p.name}`:''}`;if(item.profileUrl){profile.href=item.profileUrl;profile.style.display='inline-block';profile.textContent=item.type==='sponsor'?'Visit Sponsor':'View Band Profile';}else{profile.href='bands.html';profile.style.display=item.type==='sponsor'?'none':'inline-block';profile.textContent='View Band Profile';}}
function renderRecent(p,index){if(!recent)return;recent.innerHTML='';if(!p?.items?.length){recent.innerHTML='<li>No tracks played yet.</li>';return;}for(let n=1;n<=Math.min(5,p.items.length);n++){const i=(index-n+p.items.length)%p.items.length;const x=p.items[i];const li=document.createElement('li');li.innerHTML=`<span>${esc(x.type==='sponsor'?'Sponsor':x.artist||'Unknown')}</span> — ${esc(x.title||'Untitled')}`;recent.appendChild(li);}}
function empty(){cover.src=DEFAULT_COVER;title.textContent='BANDtroductions Radio';artist.textContent='No scheduled programming yet';profile.href='radio-submit.html';profile.textContent='Submit Music';audio.removeAttribute('src');audio.load();if(recent)recent.innerHTML='<li>No tracks played yet.</li>';}
function countPlay(item){if(item.type!=='track'||!item.id)return;const marker=`${item.id}-${Math.floor(Date.now()/10000)}`;if(lastCounted===marker)return;lastCounted=marker;runTransaction(ref(db,`RadioTracks/${item.id}/playCount`),v=>(v||0)+1).catch(()=>{});}
async function sync(force=false){const state=currentState();if(!state){empty();return;}const {playlist:p,pos,item}=state;const key=`${p.id}|${pos.index}|${item.id||item.title}`;setMetadata(item,p);renderRecent(p,pos.index);const src=item.audioUrl||'';if(!src)return;const absolute=new URL(src,location.href).href;const changed=audio.src!==absolute||currentKey!==key;if(changed){const resume=userWantsPlay;switching=true;currentKey=key;audio.src=src;audio.load();audio.addEventListener('loadedmetadata',()=>{try{audio.currentTime=Math.min(pos.offsetSeconds,Math.max(0,(audio.duration||pos.offsetSeconds+1)-.25));}catch{}switching=false;if(resume)audio.play().catch(()=>{});},{once:true});return;}if(audio.readyState>0&&(force||Math.abs((audio.currentTime||0)-pos.offsetSeconds)>3)){try{audio.currentTime=pos.offsetSeconds;}catch{}}}

audio?.addEventListener('play',()=>{userWantsPlay=true;sync(true);const s=currentState();if(s)countPlay(s.item);});audio?.addEventListener('pause',()=>{if(!switching)userWantsPlay=false;});audio?.addEventListener('ended',()=>sync(true));
const genreBar=document.querySelector('.radio-card-genres');if(genreBar){genreBar.innerHTML='<span style="color:#8fa09d;font-size:.75rem;font-weight:800">📡 LIVE SCHEDULE · everyone hears the same rotation</span>';}
onValue(ref(db,PLAYLIST_PATH),s=>{playlists=s.val()||{};sync(true);});onValue(ref(db,'RadioTracks'),s=>{tracks=s.val()||{};sync(true);});setInterval(()=>sync(false),1000);
